#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/pyfabricate/pyenv-3.12.4/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwY'
    b'AAAGlUlEQVR4nO1b328URRxfXgT8J1QETUTRROSVB9qdLSEi1iMBa/RBixgVSCz6ArWYdmZb'
    b'sJRWC30yCC/+aIHQKgYoMb2ZPSiUQnmRUrGNvIBKi0Ih7I757O6Vo732rnd7s9uGbzLJ5X7t'
    b'fj47853vj89o2iNTZ6squx8vru16iVBeZFAeI1S8g+G95kX4LLaLz9dmhUk5p4TxFwgVm3TG'
    b'DxEmBgnlDmFCTjm87wz6v/m4uDr+PP5Lmylm1HY9Taj43GD89ySolTsT9lstl+T7B67IirZr'
    b'clvHDbnjl38kPTHsDrzGe/gM3ylruSRX1iXsB6SIAZ3xSvy3FlXTGV+mU344+ZRL95xztvww'
    b'JGtODMvmM/fl3m57WgO/ATmbvx+SpY09HhmUO5gZRk38FS0qVlKTeIYw8RNu0DCFs+HbfklP'
    b'jkwbcKZBTw7L8v397jW8mcHbi0yxKDTgyys75+mMf0GYuGsw4XxwcEDWx+8EDnz8qO+6Izce'
    b'GJC4Jq5NmKgyGjrmKgVPqHiSMHEaT2L93j6n9tStggMfP3b++p8sa+lLOtVzeg1fqAS8Qfka'
    b'wsQtw7TsrW3XZLNi4A/5iW7bdZwGs0DECKHW6oKCJ4xv0Jmw1zSctVln8Os8d/8wIl/bfdbG'
    b'venUKi8IeJ2JzzDd1n7Va+/mo6GDHj8a+Khc23jeXRI6FZ8G/uSJv96brHuhg51sNFr35Prm'
    b'ix4JTLwX2JrXmbDx5KMMPpUEzATcMzHFq3mBLzLFImKKW1jzUZz2Uy0H+AQ4xpyjR6OhYy62'
    b'F3jYIBzeN+dt2f6bo9Qx+rvDhZwSLN0LciS2uiDA/3VbSseR8viAOhKwRfpxQtX0pz4To3Ao'
    b'zQGBT5pKEnDvb+5zg6W7xOx6Nvunb4qfEWrWnfo3UPBhkIAoFVh0xo9mO/WXYdogti8E+DBI'
    b'QIoNTEVmYmlmAig/DMa+7Lqd10Xh8GxHTmn4/Fi/oySBcrNIKtqyKGZwN6UN4sIdlx15PwMJ'
    b'qmYCUmlgW0FPL5iUAMJEFaYKCzCfjwoJqCd4YTLfnh69lHNQxkL1JeiLR4UEv7J0JW2N0agV'
    b'S8AQyliFuHgUSNj83aAfFyQWp/P+m/EhaniFuoGwSag+cdNbBox/mI6AQ6je5lLAnCkkfH3m'
    b'vltt1plonegATTGEcnQhwUeBhLJ9fZKY4o8JHRudcXvjwStKCAiTBARFwPpQgqRT60WsDSQP'
    b'qggIi4SKVi9BQtdKe7D/xwne3N5xQykBYZCADpRfMSpOmQGiFG+iRaWaANUk7Dj2t0sAKl3a'
    b'2AxAlxZb4PGboRCgkoTkVljM+NuRIgBJkYrkKS0BeshLQBX4SZdAcY2lh+UEVYKfwglaoWyD'
    b'qsFjfNL658RtMLaLz1cdCIUBPjUQQndbeygUZmJQVSgcFvixUJiJqxNzASraVCRDYYIfS4Yo'
    b'/zEdAZuwNiBLmY3gMaqPT5EOl0DRxYSryZmN4FMLIka19dwEAjQp50CNVbon+JJYFMBnLInB'
    b'IG9zl0GARdGogMfS9ttk27RMZfHy/f2zCjxG+f7LmcviMFeHx4RTP4saI2jyoDGS1vuPN4gQ'
    b'MVUgRcu3NXbjdvjgU1tjOrVe1rIxnfGjmAX5yt8mI0EleLPTa44SJo5kBR4GzR3a4+uaLwTS'
    b'Hk8lQSV43Dt0TWiPQ9GqTceI3yYLIkFKkqASfGriA6G1lotExmDiLKZPENGheonMsOv4DMa7'
    b'c5bSGtgWmRiB4AjCI1U3n+/YHR+Vq+tdkdRwxm0vk0F+CslZrKnXhgQtbHCZBu4x1nTeU42a'
    b'8VVaEKZTq9wVSjZfdKJMAu5tHYSSOLNA+buBgE8a5KeuVLapN5LLAdM+1tjjgWd8q1YI06lV'
    b'jqkFn1CIQxH5ODyseVcdGvSTH2+QnxIqRiCXr4iAXB5bnX+KZDiwNZ/JVtbFnyCMW1gSWHNh'
    b'HJjANdfv9YTRrqJV9YEqw5PSIlgaRayAeDtfZVk2A0karuWHt6MIcmKVfY9pYZlewxcid0ge'
    b'mkIqjTUZNHAoV5DS+sDx1I9E6hhdkZlYisLq2LG5xh4bJSi0onIptKKAiRoe/uP1PanH5kRr'
    b'1lldGLaCnl6AaYnS09jBybqEXdbS5x2cbL0mt7Vfd9tw6EViuAcn26+7Ds09OLmvb/zByX7I'
    b'24rrrKe0mWSEJRbrlH+EpwZZChoSmY7O+t+5iuIFqrfpC5gz1JZXds5z5Xg4KM2sN9ChxXCb'
    b'szhQXSuWTOjYPDKtoPY/TuK3Y51R7LIAAAAASUVORK5CYII=')

