
from unittest import TestSuite
from unittest import main as unitTestMain


from codeallybasic.UnitTestBase import UnitTestBase

from pyfabricate.steps.Validator import validateEmail


class TestEmailValidator(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 13 October 2024
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testValidEmailAddress(self):

        email: str   = "Humberto.A.Sanchez.II@gmail.com"
        valid: bool = validateEmail(email)

        self.assertTrue(valid, 'Should have passed')

    def testInvalidEmailAddress(self):

        email: str   = "Humberto.A.Sanchez.II@gmail"
        valid: bool = validateEmail(email)

        self.assertFalse(valid, 'Should fail')


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestEmailValidator))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
