#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/pyfabricate/pyenv-3.12.4/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAIRlWElm'
    b'TU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAAB'
    b'AAIAAIdpAAQAAAABAAAAWgAAAAAAAABIAAAAAQAAAEgAAAABAAOgAQADAAAAAQABAACgAgAE'
    b'AAAAAQAAABCgAwAEAAAAAQAAABAAAAAAx28c8QAAAAlwSFlzAAALEwAACxMBAJqcGAAAAVlp'
    b'VFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6'
    b'bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDYuMC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRm'
    b'PSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAg'
    b'PHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6dGlmZj0i'
    b'aHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRh'
    b'dGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAg'
    b'PC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KGV7hBwAAArpJREFUOBF1U0tIVGEUPv9/HzPOjFaD'
    b'z7RoahyhbDFE67SSRIpkgtqIi3YtdOG+GGoVQRuXRUFRYJBRqJRS2q5yIZFZanMHHwgzqZmP'
    b'Zrxz7z2dc8cJKzyXC/e///nO+b7zELBlDfFhdSTeaPHR1zUQjUVqGkv8RSE+r25kkj1T88O5'
    b'2y1jfN7uy2eIE9j9aO+NdD5ODN4cXsM7nxDvf8m/d8cR+R/fAflsx4hCtOi1N6fOHj/8Mlxb'
    b'oZpZcBwbHQAERAAbBXg0ITUvyG/Taatv9HPz2PWTrxkr3MyXn9RdjZ0YPxQqVzezaDqOo0sh'
    b'wCKwRwEIaACpXwhFqjQ1r9ANI23dePa2Hu5dnJQcoPP0se5wOA9GRBdM6d0AZw4KuFQvodIn'
    b'wLRRz1GCcG25yhjGSl/XULS6qqLJpU2ZmZJDmXMUoTUsoGaXgPmfCGs5AIXSMTv2ra4qbwIq'
    b'toxF9jYGS/3Ampm2TWCTwOdrBezfI2B2BaF3EmHTpmycknyoOnawNABt1Cm1xK+HVNJpcsGY'
    b'ElG4UCegmjIbywj9CXTrwMz4no1YCA/RKfb5DkhgsTtYvsI7XG79lquZTNIiesSNnrz+p0SZ'
    b'qYeCAlpJCkvijhQCSimRMeuZbFLyhC0vboBUhHSo6Qp56ST2+TTCzA+EfbsFxCI0BySTi8uD'
    b'ISQoy4vr8HB8dkTyeM4tpIZ0GhIys1AHbSvIHDHhehTTLHCB2Yd95xe+D0J3yxjFBfgQaHh/'
    b'tDJ4pawsoNk2MUZUuCPMeWYFYHoJIbWB4KVB0mmQEkY6d+vF6Dn42LMkeRzhQWyqb3SiOZFM'
    b'57x+oaua4lC7LFWCRdqtpayw/F7F8dBdwkhZ/e++NjPGxTKD+LZl6nhkvPqzTBN/LxPf/bdM'
    b'HICNoxXWGToGom1HaJ2L8uu8lt00uGCs+V/f3x5+bCpKhY3bAAAAAElFTkSuQmCC')

