#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/pyfabricate/pyenv-3.12.4/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwY'
    b'AAAGhklEQVR4nO1b228UVRifvgj4T6gImoiiicgrD7RzBkJErEsC1uiDFjEqNRH0BWox7TnT'
    b'gqW0WuiTqfDipQVCqxigxHTPmYVyKZQXKRXbyAsEaVEppDPH/OZSynbb3W7n1g1f8iWbvc38'
    b'vjnfd77L7yjKIwlP1lT2PF5S2/0SobxYozxBqHgH6rzmxfgssZsvUApCpCxaxfgLhIotKuOH'
    b'CBODhHKLMCGnVec7g+5vPi6pTj6P/1Lmimi13U8TKr7QGP/DA7V6V8p8q+WyfP/AVbm1/brc'
    b'3nlT7vz1b0lPDNuK13gPn+E7ZS2X5eq6lPnAKGJAZbwS/63EVVTGl6uUH/aecunec9YnPw7J'
    b'mhPDsvnMmNzXY85I8RsYp+KHIVnaeN4xBuUWVoZWk3xFiYusqkk9Q5j4GTeo6cLa9F2/pCdH'
    b'Zgw4m9KTw7K8td++hrMyeEexLhZHBnxFZdd8lfEvCRP3NCasDw4OyPrkXd+Bp2t99125+cCA'
    b'xDVxbcJEldbQOS9U8ISKJwkTp/EkNu7rs2pP3QkceLru+u1fWdbS5wXVc2oNXxQKeI3ydYSJ'
    b'O5pumNvar8vmkIE/FCd6TDtwasyAIUYINdYGCp4wvkllwlzXcNZkXf77ef7xYUS+tuesiXtT'
    b'qVEeCHiVic+x3NZ/3Wvu4aORg07XBj4q1zdesF1CpeIz3588cf29ybgfOdiptNG4Lzc2X3KM'
    b'wMR7vvm8yoSJJx9n8BONgJWAeya6eHVW4It1sZjo4g58Po7Lfjp3QExAYMw7e9QaOudhe0GE'
    b'DTPgdfxuyW8v+BMY3d3hYl4FluokORJbXVjgj/Vb0rSkvHVXytbe2f8ftkg3T6ia+dJnYhQB'
    b'pTlk8J74YQTc+5v77WTpHtG7n8396eviF6Sadaf+iQS8n0ZAlgosKuNHc136y7FskNtHCd5P'
    b'I6DEBqZiPbUsuwEoPwyLfdX9X+TgIfgcgXG2BZRdRVLRnkMzg9slbVzA43t+XA+lNLCtpKcX'
    b'TmkAwkQVlgoLoJ6PErzXT3DSZL4jM3opi9DGQvel0MB76naWrmbsMWq1YikshDZWIYKHVnw/'
    b'6OYFqSWZon8FPkQPrxDBQ6tP3HbcgPEPMxngELq3+TQw5wJ46Ddnxuxus8pE2+QAqIshtKML'
    b'FbynZfv7JNHFn5MmNirj5uaDVwsavJcUAetDBZJKjRfhGygeChk8dGubUyBhaqU82P+TBG/u'
    b'6LxZ0OChmEC5HaOSCStAlOJNjKgKGTx057FbtgHQ6VLGVwCmtNgCj98uaPATt8ISxt/23QCd'
    b'Vyw5lsUAliXl8YGYGUD10QXiboSMLlBSY6h+BsE4G2GKIGj4vg3G1Qiftv01eRtM7OYLgkiE'
    b'4mgELxHCdFt5KBVmYjCIVDhuRrBTYSauTa4FqGgPqhiKixHGiyHKf8pkgC3wDdBSgrh4HIxQ'
    b'fXyacngVGF1M2JycoG4gaiN4DRGt2nhukgEUKYvAxirdG2xLLEojTNsSg4DeZrtBwE3RKIwA'
    b'13bHZNuVbG3x8tbg2+JhG6G89Ur2tjjE5uExYdUX0GAEQx4MRjJG/3QBCRFLBVS0oA2Qy0rw'
    b'czSmUuNlJRdRGT+KVRAW/W0qI/gBXu9yhqOEiSM5gYeAc4fx+Ibmi6GNx9ON4Nd4HLwmjMfB'
    b'aFVmIsQdk/lZIOVqBL8IEl7hA6K1kg9FRmPiLJZPUNlhsBSZYTvwaYz35E2l1bAtMjECwhGI'
    b'R2EZYba6Jzkq19bbJKnhrNteNgH9FJSzRFOvCQpa1OCyKe4x0XTBYY3qyTWKH6JSo9wmSjZf'
    b'suJsBNzbBhAlcWaB8nd9Ae8J6Kc2VbapN5bugGWfaDzvgGd8mxKEqNQox9JCTAi6XphpwIPP'
    b'2+xQv598uoB+SqgYAV1+awzo8tjq3FMkw775fDZZXZd8gjBuwCXgc1EcmMA1N+5ziNE2ozXs'
    b'A1WaQ6VFsjSKXAH5dhjMMhRpuJab3o4iyUlU9j2mRCVqDV+E2sE7NIVSGj7pN3AwV1DSusDx'
    b'1I/E6hhdsZ5ahsbq+LG5xvMmWlAYReXTaEUDEz08/MfreycemxNtOVd1UchKenohliVaT+MH'
    b'J+tSZllLn3Nwsu263N5xwx7DYRYJtQ9OdtywA5p9cHJ/X/rByX7Q20rqjKeUuSSEpZaolH+E'
    b'pwZaCgYS2Y7Out+5huYFureZG5hzVFZUds236Xg4KM2MNzChhdrDWRyorhVLJ01sHokSqPwP'
    b'iIS3Y9x49SQAAAAASUVORK5CYII=')

