#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/pyfabricate/pyenv-3.12.4/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAAsTAAALEwEAmpwY'
    b'AAAGwElEQVR4nO1b229URRg/vAj4T6gImoiiicgrD7RnDoSIWJcErNEHLWJUaiLoC1Qw7cxp'
    b'wVJaLfQRISReyiVQb5QS0p05C+W+PAkFIfICUVpUFrpnx/zOOVvKdununnuVL/mSZnc7c37f'
    b'+Wbmu/xGUR5KeLK4YeDR6ub+FwjlVRrlCULFW1D7b16F7xKb+XTlPyFSTlnI+HOEitUq43sJ'
    b'E1cI5TnChJxQ7d9ccf7nw+rG5LMYS5ksojX3P0mo+Exj/FIe1KJNKfONrvPy3Z0X5Zo91+S6'
    b'nhty489/Sto7ZCn+xmf4Dr+p7TovF7WkzHtGEYMq4w0YW4mrqIzPUynfl3/LNVtP5j767qps'
    b'6h2SncezctuAWZHif2Cc+m+vypr2U7YxKM/BM7Sm5EtKXGRhU+opwsQPeEBNF7mVX1+Q9PBw'
    b'xYBLKT08JOt2XLDmsD2DH6zSxazIgM9v6JumMv45YeKOxkTuvV2DsjV523fghdraf1uu2jko'
    b'MSfmJkxs0Np6poYKnlDxOGHiGN7Eim3pXPORW4EDL9RNR/+WtV3p/KZ6Um3iM0MBr1G+lDBx'
    b'S9MNc+2ea7IzZOD37RMDprVxasyAIYYJNZYECp4wvlJlwlzadsJkff6vc/f7w7B8ZcsJE8+m'
    b'UqMuEPAqE5/C3ZZ9ecbcwjORgy7UNp6Ry9pPW0tCpeIT3988cdZ7h3E3crAP0nbjrlzRec42'
    b'AhPv+LbmVSZMvPk4gx9rBHgCnpno4mVP4Kt0MYvo4hbWfBzdfqLlgD0BG6Pr6FFr65mK4wU7'
    b'bJw2vEo2Rud0OOsqwVLtIEfiqIsajFvFEenECRsqd30mMthQojznvSqe/fXtVrB0h+j9T5f/'
    b'9nXxI0LNliN/RQ7CqyJKBRaV8QPluv48uA1i+6gf3i9Fig1MVXpqbmkDUL4PFvui/x/XE/4y'
    b'aMpMVsrdae8Pv+usPdbhS94SKCuLpGJPGcUMbqW0XsDnpC1Z05sRAH7EdAaT3oyAVBrYFtBj'
    b'Mx5oAMLEBrgKc5nPjwUvPRqhELxXI6CeYIfJfH1x9FJOQRkL1Re3VoarFpORCo2A3xYDD8Ec'
    b'bp/PqSxdLFpj1JrFHFgIZSy/XNaNJ0w0RqWGLNT6b644cUFqdrHdvx5foobndgKvRggSPLSx'
    b'96a9DBh/v5gB9qJ666aA6YcRggYP/ep41qo2q0x0j98AdXEV5Wivk7gxQhjg81q7PS2JLn4b'
    b'17FRGTdX7bro20TlGiFM8PmgCFjvS5BUajyPtYHkwc/JoLvPTWyEMMFD13TbCRK6Vsq98z9J'
    b'8OH6nhu+T1jKE8IED0UHyqkYVY/xAFGDD9GiCmLSSowQJHjoxp/+sAyASpcy6gHo0uIIPHQz'
    b'sInLMUI2Fyz4sUdhNeNvPjRAHJdANoolUN1kqHHaBLPhb4JGNMdgLvxj8OPu38cfg4nNfHrY'
    b'gVAeoB8JlJtACN1tZayAlhJWKFz4dsM0ghUKM3H5PvAQlIvCSIYe5NphGGE0GaL8e6VQCBWr'
    b'sTZASwkbfFhGaDw0QTq8EIwuJixOThTgwzBCviCiNRrPjDOAIuUUsLFqtv5PS2IQ0NusZeBj'
    b'UXQkLkXRXrsoSphYp5Qqi9ft8KcsPhKrsvivpcviEIuHx0Su1UNj5JCPjRGMgbEwptsx0ORB'
    b'Y6To7l8oICHCVUBF8/rwcWuNqdR4USlHVMYPwAuioL/5rXqf3RwlTOwvCzwEnDu0x5d3np30'
    b'7XHwmtAeB6NVqUSI0yYLIkEKS/OJD4jWihuKjMbECbiP1+gwCkUvEBufxviAayqthmORiWEQ'
    b'jkA8ihpUubolmZFLWi2S1FDJY6+UgH4Kylmi44wJClrU4EopnjHRcdpmjerJxYofolKjziJK'
    b'dp7LxdkIeLblIErizgLlb/sCPi+gn1pU2Y4zsVwOcPtE+ykbPONrlSBEpUYdXAt7QhCXIrxs'
    b'eFjzFjvU7zdfKKCfEiqGQZdfEwO6PI465xbJkG9rvpQsakk+Rhg3sCSw5qKIGDHnim02Mdpi'
    b'tIZ9oUqzqbQIljKIFRBve2GWlatI0jCXE95mEOQkGtKPKFGJ2sRnInfIX5pCKo016TdwMFeQ'
    b'0jrA8db3x+oaXZWemovC6ui1ufZTJkpQ6MW5KbSigIkaHsZ4devYa3Oiu+ysLgpZQI/NgFui'
    b'9DR6cbIlZdZ2pe2Lk93X5LqD1602HJqxUOvi5MHr1oZmXZzcni68OHkB9LbqFuMJZTIJYanZ'
    b'KuUf4K2BloKGRKmrs85vLqN4gept8QLmJJX5DX3TLDoeLkoz4zW0qKFWcxYXqpvFnHEdm4ei'
    b'BCr/An4qvejyBtnPAAAAAElFTkSuQmCC')

