#----------------------------------------------------------------------
# This file was generated by /Users/humberto.a.sanchez.ii/PycharmProjects/pyfabricate/pyenv-3.12.4/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

embeddedImage = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAIRlWElm'
    b'TU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAAB'
    b'AAIAAIdpAAQAAAABAAAAWgAAAAAAAABIAAAAAQAAAEgAAAABAAOgAQADAAAAAQABAACgAgAE'
    b'AAAAAQAAABCgAwAEAAAAAQAAABAAAAAAx28c8QAAAAlwSFlzAAALEwAACxMBAJqcGAAAAVlp'
    b'VFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6'
    b'bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDYuMC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRm'
    b'PSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAg'
    b'PHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6dGlmZj0i'
    b'aHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRh'
    b'dGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAg'
    b'PC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KGV7hBwAAAqxJREFUOBFtU01MU0EQnt33+ihtRYMU'
    b'DKIRLcUoHhri0QjqoSESTU04EQ/ePMCBu6bRk5p44ajRRKMJHkQJEgUVvKkciBFBwLYBCQmV'
    b'IvKT/rz3dpx5jyYIbtKf3fm+b77Z2RGwuZriw/pIvNnira9rIBIL1zSX+Utreb+6kU31TM8P'
    b'm3dbxni/Fct7iBPZ+XP5ebjzaWLw1vAa3h9HfDjpfu59ReQzjgFhtnJEUS1y/f3Z8yePvQ7V'
    b'VelmDlTeRCUFghQMFyA1IQ0vyB8zaat/9Ft07MaZd8x1wnDlWf212OnxI7WVeiGHhaypjCq/'
    b'gHUTIG8DMEohiUlZKPEKI5FMWzd7PzTAg7Ypyfqd5xq7QyGXXLDRIbc1SIgeFmAjk4GcCEBE'
    b'I08JQnWVOnOYq/m6hiKtjUdvGx5DKVvpgjwzKegDqNktoNoPMJnhIljEcaIhSuXRPaG3e0/1'
    b'yVi4urm8wg/KRgWUhS2x7d4phNnfCAf2CLhQJ8AkURZ2nCiwyysC0E6dkmV+o1bXgO2xI+Bv'
    b'rrmEzl7OICQzrsilehKnc44TVjBnl893SIJi2v8XGXK908+m/g6gvprNpiyyLNxLcmq1KI1F'
    b'whfDAg5SCXMrCC+mETxUn0aihEXmrGdzKckvbHlpw+kzp2FDbD9GlotkLsXYJHM7hQRteWkd'
    b'Ho/PjUh+nj8XFof4kXCfbVIIeAD2Uwfm/1BmInPmYv2MYez8wq9B6G4Zo1wAnwNNn07sK78a'
    b'DBJVQWElh9rsits+rp1tb3tI5p2+0Vb40pOR/BzhUWy6f3QimkilzRK/MAJeTWVywqJ7sHQp'
    b'LCra0j2a8lIskVy0Xn38HmWOw2UH8S3D1PEk+eafYZpALA4Tx3YMEwvwYrXiOEPHQKT9OI1z'
    b'qTvOa7l8ki+Ma96O/QsZj2fog0kszQAAAABJRU5ErkJggg==')

