
version: '2.1'
#
# Install one python so unit test passes
#
orbs:
  python: circleci/python@2.1.1

workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: cimg/python:3.12
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y
            whereis pyenv
            whereis direnv
            pyenv install --list
            pip install --upgrade pip
            pip install wheel
            pip install setuptools
            pip install semantic-version==2.10.0
            pip install buildlackey==1.8.1
            pip install html-testRunner==1.2.1
            pip install codeallybasic==1.10.0
      - run:
            name: run tests
            command: | 
              pyenv install 3.12.0
              unittests -v loud
