
version: '2.1'

orbs:
  python: circleci/python@2.1.1

workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: cimg/python:3.10-browsers
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y
            sudo apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl 
            sudo apt install -y llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git
            pip install --upgrade pip
            pip install wheel
            pip install setuptools
            pip install click==8.1.7
            pip install PyGithub==2.4.0
            pip install semantic-version==2.10.0
            pip install buildlackey~=1.6.3
            pip install html-testRunner~=1.2.1
            pip install codeallybasic==1.4.0
      - run:
            name: run tests
            command: | 
              unittests
